In [95]:
import pandas as pd
df = pd.read_excel("D:\\myProjects\\exceltocsv\\exceltocsv.xlsx", sheet_name=0)
df

     Row Labels  Sum of index1  Sum of index2  Sum of index3
0             A             15             20             25
1            a1              1              2              3
2            a2              2              3              4
3            a3              3              4              5
4            a4              4              5              6
5            a5              5              6              7
6             B             30             34             38
7            b1              6              7              8
8            b2              7              8              9
9            b3              8              9             10
10           b4              9             10             11
11            C             33             36             39
12           c1             10             11             12
13           c2             11             12             13
14           c3             12             13             14
15  Grand Total             78             90            102

In [63]:
print(range(len(df.index)))

range(0, 16)

In [96]:
gbm=[]
gbm_list = ['A','B','C']
col = ['gbm','dept','index1','index2','index3']
prev = ""
for r in range(len(df.index)):
    if r==0 :
        prev = df.iloc[r,0]
    elif df.iloc[r,0] in gbm_list:
        prev = df.iloc[r,0]
    gbm.append(prev)
df.insert(0,'gbm',gbm)
df.columns = col
#print(df)
df1 = df.iloc[list(df['dept']!=df['gbm'])]
df2 = df1.drop(df1.tail(1).index)
df2.reset_index(drop=True, inplace=True)
print(df2)

   gbm dept  index1  index2  index3
0    A   a1       1       2       3
1    A   a2       2       3       4
2    A   a3       3       4       5
3    A   a4       4       5       6
4    A   a5       5       6       7
5    B   b1       6       7       8
6    B   b2       7       8       9
7    B   b3       8       9      10
8    B   b4       9      10      11
9    C   c1      10      11      12
10   C   c2      11      12      13
11   C   c3      12      13      14

In [93]:
import pandas as pd
df_b = pd.read_excel("D:\\myProjects\\exceltocsv\\exceltocsv.xlsx", sheet_name=1)
df_b

    Row Labels  Sum of index1  Sum of index2  Sum of index3
0            A             23             25             27
1           a1             11             12             13
2           a6             12             13             14
3            B             33             35             37
4           b1             16             17             18
5           b5             17             18             19
6            C             41             43             45
7           c1             20             21             22
8           c4             21             22             23
9  Grand Total             97            103            109

In [94]:
gbm=[]
gbm_list = ['A','B','C']
col = ['gbm','dept','index1','index2','index3']
prev = ""
for r in range(len(df_b.index)):
    if r==0 :
        prev = df_b.iloc[r,0]
    elif df_b.iloc[r,0] in gbm_list:
        prev = df_b.iloc[r,0]
    gbm.append(prev)
df_b.insert(0,'gbm',gbm)
df_b.columns = col
#print(df_b)
df_b1 = df_b.iloc[list(df_b['dept']!=df_b['gbm'])]
df_b2 = df_b1.drop(df_b1.tail(1).index)
df_b2.reset_index(drop=True, inplace=True)
print(df_b2)

  gbm         dept  index1  index2  index3
0   A            A      23      25      27
1   A           a1      11      12      13
2   A           a6      12      13      14
3   B            B      33      35      37
4   B           b1      16      17      18
5   B           b5      17      18      19
6   C            C      41      43      45
7   C           c1      20      21      22
8   C           c4      21      22      23
9   C  Grand Total      97     103     109
  gbm dept  index1  index2  index3
0   A   a1      11      12      13
1   A   a6      12      13      14
2   B   b1      16      17      18
3   B   b5      17      18      19
4   C   c1      20      21      22
5   C   c4      21      22      23

In [99]:
df_merged = df2.merge(df_b2,how='outer',on=['gbm','dept'],sort=True, suffixes=('_1','_2'))
df_merged

   gbm dept  index1_1  index2_1  index3_1  index1_2  index2_2  index3_2
0    A   a1       1.0       2.0       3.0      11.0      12.0      13.0
1    A   a2       2.0       3.0       4.0       NaN       NaN       NaN
2    A   a3       3.0       4.0       5.0       NaN       NaN       NaN
3    A   a4       4.0       5.0       6.0       NaN       NaN       NaN
4    A   a5       5.0       6.0       7.0       NaN       NaN       NaN
5    A   a6       NaN       NaN       NaN      12.0      13.0      14.0
6    B   b1       6.0       7.0       8.0      16.0      17.0      18.0
7    B   b2       7.0       8.0       9.0       NaN       NaN       NaN
8    B   b3       8.0       9.0      10.0       NaN       NaN       NaN
9    B   b4       9.0      10.0      11.0       NaN       NaN       NaN
10   B   b5       NaN       NaN       NaN      17.0      18.0      19.0
11   C   c1      10.0      11.0      12.0      20.0      21.0      22.0
12   C   c2      11.0      12.0      13.0       NaN       NaN       NaN
13   C   c3      12.0      13.0      14.0       NaN       NaN       NaN
14   C   c4       NaN       NaN       NaN      21.0      22.0      23.0