In [3]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns',None)

In [10]:
df = pd.DataFrame({'a':['1','2','3','4','5','6','7','8','9','10'],\
                   'b':['b1','b1','b1','b2','b2','b2','b2','b3','b3','b3'],\
                   'c':['1','1','0','1','1','1','0','1','1','0']})

In [19]:
df[['a','c']] = df[['a','c']].astype(int)

In [34]:
grouped = df[df['c']==1].groupby('b').agg({'a':['count','sum','mean','median']})

In [35]:
grouped.columns = ['_'.join(x) for x in grouped.columns.ravel()]

In [36]:
grouped.columns

Index(['a_count', 'a_sum', 'a_mean', 'a_median'], dtype='object')

In [7]:
s1=pd.Series(['c1','c3'], index=[1,3])
df['c'] = s1

In [8]:
df

   a    b    c
0  1   b1  NaN
1  2   b2   c1
2  3   b3  NaN
3  4  NaN   c3

In [18]:
df.dtypes

a    object
b    object
c    object
dtype: object

In [20]:
df['d'] = pd.Series([1,3],index=[1,3])

In [21]:
df

   a    b    c    d
0  1   b1  NaN  NaN
1  2   b2   c1  1.0
2  3   b3  NaN  NaN
3  4  NaN   c3  3.0

In [30]:
[type(df.loc[i,'a'])==str for i in range(len(df.index))]

[True, True, True, False]

In [32]:
type(df.loc[2,'a'])

str

In [37]:
df

    a   b  c
0   1  b1  1
1   2  b1  1
2   3  b1  0
3   4  b2  1
4   5  b2  1
5   6  b2  1
6   7  b2  0
7   8  b3  1
8   9  b3  1
9  10  b3  0

In [41]:
df['d'] = df.groupby('b')['a'].cumsum()

In [60]:
s = "-0.98"
s1 = float(s)
type(s)

str

In [43]:
tuples = list(zip(*[['bar', 'bar', 'baz', 'baz', 'foo', 'foo', 'qux', 'qux'],
                    ['one', 'two', 'one', 'two', 'one', 'two', 'one', 'two']]))

In [44]:
tuples

[('bar', 'one'),
 ('bar', 'two'),
 ('baz', 'one'),
 ('baz', 'two'),
 ('foo', 'one'),
 ('foo', 'two'),
 ('qux', 'one'),
 ('qux', 'two')]

In [3]:
import pandas._testing as tm

ModuleNotFoundError: No module named 'pandas._testing'

In [10]:
tuples = list(zip(['bar','bar','baz','baz'],['one','two','one','two']))

In [11]:
import pandas as pd
index = pd.MultiIndex.from_tuples(tuples, names=['first','second'])

In [12]:
import numpy as np
df = pd.DataFrame(np.random.randn(4,2), index=index, columns=['A','B'])

In [13]:
df

                     A         B
first second
bar   one     0.658356  0.176461
      two    -0.398986 -0.334053
baz   one     0.309660 -1.385591
      two    -0.037579 -0.802666

In [14]:
stacked = df.stack()

In [15]:
stacked

first  second
bar    one     A    0.658356
               B    0.176461
       two     A   -0.398986
               B   -0.334053
baz    one     A    0.309660
               B   -1.385591
       two     A   -0.037579
               B   -0.802666
dtype: float64

In [17]:
stacked.index

MultiIndex([('bar', 'one', 'A'),
            ('bar', 'one', 'B'),
            ('bar', 'two', 'A'),
            ('bar', 'two', 'B'),
            ('baz', 'one', 'A'),
            ('baz', 'one', 'B'),
            ('baz', 'two', 'A'),
            ('baz', 'two', 'B')],
           names=['first', 'second', None])

In [18]:
stacked.unstack()

                     A         B
first second
bar   one     0.658356  0.176461
      two    -0.398986 -0.334053
baz   one     0.309660 -1.385591
      two    -0.037579 -0.802666

In [19]:
stacked.unstack(1)

second        one       two
first
bar   A  0.658356 -0.398986
      B  0.176461 -0.334053
baz   A  0.309660 -0.037579
      B -1.385591 -0.802666

In [20]:
stacked.unstack(0)

first          bar       baz
second
one    A  0.658356  0.309660
       B  0.176461 -1.385591
two    A -0.398986 -0.037579
       B -0.334053 -0.802666

In [21]:
index=pd.MultiIndex.from_product([[2,1],['a','b']])

In [23]:
df = pd.DataFrame(np.random.randn(4), index=index, columns=['A'])

In [24]:
df

            A
2 a -1.970151
  b  1.060340
1 a -0.250399
  b  0.799146

In [27]:
df.stack().unstack() == df.sort_index()

        A
1 a  True
  b  True
2 a  True
  b  True

In [31]:
columns = pd.MultiIndex.from_tuples([('A','cat','long'),('B','cat','long'),('A','dog','short'),('B','dog','short')], names=['exp','animal','hair_len'])

In [32]:
df=pd.DataFrame(np.random.randn(4,4), columns=columns)

In [33]:
df

exp              A         B         A         B
animal         cat       cat       dog       dog
hair_len      long      long     short     short
0        -0.797950  0.053858 -0.270587 -0.237236
1        -0.739371 -1.700968 -0.441694  0.308524
2        -0.954579  2.335735 -0.748556 -2.592291
3        -1.078627  0.224992 -0.578583 -0.468241

In [35]:
df.stack(level=[0,1])

hair_len          long     short
  exp animal
0 A   cat    -0.797950       NaN
      dog          NaN -0.270587
  B   cat     0.053858       NaN
      dog          NaN -0.237236
1 A   cat    -0.739371       NaN
      dog          NaN -0.441694
  B   cat    -1.700968       NaN
      dog          NaN  0.308524
2 A   cat    -0.954579       NaN
      dog          NaN -0.748556
  B   cat     2.335735       NaN
      dog          NaN -2.592291
3 A   cat    -1.078627       NaN
      dog          NaN -0.578583
  B   cat     0.224992       NaN
      dog          NaN -0.468241

In [59]:
columns=pd.MultiIndex.from_tuples([('A','cat'),('B','dog'),('B','cat'),('A','dog')], names=['exp','animal'])

In [60]:
index = pd.MultiIndex.from_product([('bar','baz','foo','qux'),('one','two')], names=['first','second'])

In [61]:
df = pd.DataFrame(np.random.randn(8,4), index=index, columns=columns)

In [62]:
df

exp                  A         B                   A
animal             cat       dog       cat       dog
first second
bar   one    -1.006723  0.333833  1.933301 -0.747886
      two     0.792578  1.182966  2.011500  2.195408
baz   one     0.048726  0.425966 -0.206523 -0.825776
      two    -0.349974 -0.426779  1.434948 -0.301025
foo   one     0.490654  1.841219 -1.150589 -0.835282
      two    -1.581313  1.145093 -1.102323 -1.351742
qux   one     1.263948 -1.351274 -0.535071 -1.753001
      two    -0.797242  0.894865  0.572618 -0.269784

In [41]:
df2 = df.iloc[[0,1,2,4,5,7]]

In [42]:
df2

exp                  A         B                   A
animal             cat       dog       cat       dog
first second
bar   one    -0.137708  1.506664  1.237386  1.239354
      two    -0.686240  0.695121  0.517633  0.267951
baz   one     1.404925 -0.418373 -0.168697  0.023187
foo   one    -1.095884  0.376688  0.043044 -1.139308
      two    -1.127422  1.244934  0.234173 -0.054402
qux   two     1.532530 -1.238673  1.519890 -0.112882

In [43]:
df2.iloc[0,0] = -0.23456

D:\ProgramInUse\Anaconda3\lib\site-packages\pandas\core\indexing.py:205: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)
D:\ProgramInUse\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [44]:
df2

exp                  A         B                   A
animal             cat       dog       cat       dog
first second
bar   one    -0.234560  1.506664  1.237386  1.239354
      two    -0.686240  0.695121  0.517633  0.267951
baz   one     1.404925 -0.418373 -0.168697  0.023187
foo   one    -1.095884  0.376688  0.043044 -1.139308
      two    -1.127422  1.244934  0.234173 -0.054402
qux   two     1.532530 -1.238673  1.519890 -0.112882

In [45]:
df

exp                  A         B                   A
animal             cat       dog       cat       dog
first second
bar   one    -0.137708  1.506664  1.237386  1.239354
      two    -0.686240  0.695121  0.517633  0.267951
baz   one     1.404925 -0.418373 -0.168697  0.023187
      two    -0.580160 -0.403981  0.777685  0.436069
foo   one    -1.095884  0.376688  0.043044 -1.139308
      two    -1.127422  1.244934  0.234173 -0.054402
qux   one     0.027165 -0.623865 -1.366525  0.256863
      two     1.532530 -1.238673  1.519890 -0.112882

In [46]:
df3 = df.iloc[[0,1,4,7],[1,2]]

In [47]:
df3

exp                  B
animal             dog       cat
first second
bar   one     1.506664  1.237386
      two     0.695121  0.517633
foo   one     0.376688  0.043044
qux   two    -1.238673  1.519890

In [53]:
z = dict(zip(range(3), np.random.randn(3)))

In [57]:
for i in z:
    print(i, z[i])

0 0.25036007831332724
1 -0.7223831201163498
2 0.28463230830107167

In [58]:
z

{0: 0.25036007831332724, 1: -0.7223831201163498, 2: 0.28463230830107167}

In [65]:
df.stack()

exp                         A         B
first second animal
bar   one    cat    -1.006723  1.933301
             dog    -0.747886  0.333833
      two    cat     0.792578  2.011500
             dog     2.195408  1.182966
baz   one    cat     0.048726 -0.206523
             dog    -0.825776  0.425966
      two    cat    -0.349974  1.434948
             dog    -0.301025 -0.426779
foo   one    cat     0.490654 -1.150589
             dog    -0.835282  1.841219
      two    cat    -1.581313 -1.102323
             dog    -1.351742  1.145093
qux   one    cat     1.263948 -0.535071
             dog    -1.753001 -1.351274
      two    cat    -0.797242  0.572618
             dog    -0.269784  0.894865

In [68]:
df.stack().mean(1)

first  second  animal
bar    one     cat       0.463289
               dog      -0.207027
       two     cat       1.402039
               dog       1.689187
baz    one     cat      -0.078898
               dog      -0.199905
       two     cat       0.542487
               dog      -0.363902
foo    one     cat      -0.329967
               dog       0.502969
       two     cat      -1.341818
               dog      -0.103325
qux    one     cat       0.364438
               dog      -1.552137
       two     cat      -0.112312
               dog       0.312540
dtype: float64

In [69]:
df.stack().mean(1).unstack()

animal             cat       dog
first second
bar   one     0.463289 -0.207027
      two     1.402039  1.689187
baz   one    -0.078898 -0.199905
      two     0.542487 -0.363902
foo   one    -0.329967  0.502969
      two    -1.341818 -0.103325
qux   one     0.364438 -1.552137
      two    -0.112312  0.312540

In [70]:
df.mean()

exp  animal
A    cat      -0.142418
B    dog       0.505736
     cat       0.369733
A    dog      -0.486136
dtype: float64

In [71]:
[1,2,3]*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [78]:
import datetime
d = [datetime.datetime(2020,i,1) for i in range(1,13)]

In [80]:
for i in d:
    print(d)

[datetime.datetime(2020, 1, 1, 0, 0), datetime.datetime(2020, 2, 1, 0, 0), datetime.datetime(2020, 3, 1, 0, 0), datetime.datetime(2020, 4, 1, 0, 0), datetime.datetime(2020, 5, 1, 0, 0), datetime.datetime(2020, 6, 1, 0, 0), datetime.datetime(2020, 7, 1, 0, 0), datetime.datetime(2020, 8, 1, 0, 0), datetime.datetime(2020, 9, 1, 0, 0), datetime.datetime(2020, 10, 1, 0, 0), datetime.datetime(2020, 11, 1, 0, 0), datetime.datetime(2020, 12, 1, 0, 0)]
[datetime.datetime(2020, 1, 1, 0, 0), datetime.datetime(2020, 2, 1, 0, 0), datetime.datetime(2020, 3, 1, 0, 0), datetime.datetime(2020, 4, 1, 0, 0), datetime.datetime(2020, 5, 1, 0, 0), datetime.datetime(2020, 6, 1, 0, 0), datetime.datetime(2020, 7, 1, 0, 0), datetime.datetime(2020, 8, 1, 0, 0), datetime.datetime(2020, 9, 1, 0, 0), datetime.datetime(2020, 10, 1, 0, 0), datetime.datetime(2020, 11, 1, 0, 0), datetime.datetime(2020, 12, 1, 0, 0)]
[datetime.datetime(2020, 1, 1, 0, 0), datetime.datetime(2020, 2, 1, 0, 0), datetime.datetime(2020, 3, 1, 0, 0), datetime.datetime(2020, 4, 1, 0, 0), datetime.datetime(2020, 5, 1, 0, 0), datetime.datetime(2020, 6, 1, 0, 0), datetime.datetime(2020, 7, 1, 0, 0), datetime.datetime(2020, 8, 1, 0, 0), datetime.datetime(2020, 9, 1, 0, 0), datetime.datetime(2020, 10, 1, 0, 0), datetime.datetime(2020, 11, 1, 0, 0), datetime.datetime(2020, 12, 1, 0, 0)]
[datetime.datetime(2020, 1, 1, 0, 0), datetime.datetime(2020, 2, 1, 0, 0), datetime.datetime(2020, 3, 1, 0, 0), datetime.datetime(2020, 4, 1, 0, 0), datetime.datetime(2020, 5, 1, 0, 0), datetime.datetime(2020, 6, 1, 0, 0), datetime.datetime(2020, 7, 1, 0, 0), datetime.datetime(2020, 8, 1, 0, 0), datetime.datetime(2020, 9, 1, 0, 0), datetime.datetime(2020, 10, 1, 0, 0), datetime.datetime(2020, 11, 1, 0, 0), datetime.datetime(2020, 12, 1, 0, 0)]
[datetime.datetime(2020, 1, 1, 0, 0), datetime.datetime(2020, 2, 1, 0, 0), datetime.datetime(2020, 3, 1, 0, 0), datetime.datetime(2020, 4, 1, 0, 0), datetime.datetime(2020, 5, 1, 0, 0), datetime.datetime(2020, 6, 1, 0, 0), datetime.datetime(2020, 7, 1, 0, 0), datetime.datetime(2020, 8, 1, 0, 0), datetime.datetime(2020, 9, 1, 0, 0), datetime.datetime(2020, 10, 1, 0, 0), datetime.datetime(2020, 11, 1, 0, 0), datetime.datetime(2020, 12, 1, 0, 0)]
[datetime.datetime(2020, 1, 1, 0, 0), datetime.datetime(2020, 2, 1, 0, 0), datetime.datetime(2020, 3, 1, 0, 0), datetime.datetime(2020, 4, 1, 0, 0), datetime.datetime(2020, 5, 1, 0, 0), datetime.datetime(2020, 6, 1, 0, 0), datetime.datetime(2020, 7, 1, 0, 0), datetime.datetime(2020, 8, 1, 0, 0), datetime.datetime(2020, 9, 1, 0, 0), datetime.datetime(2020, 10, 1, 0, 0), datetime.datetime(2020, 11, 1, 0, 0), datetime.datetime(2020, 12, 1, 0, 0)]
[datetime.datetime(2020, 1, 1, 0, 0), datetime.datetime(2020, 2, 1, 0, 0), datetime.datetime(2020, 3, 1, 0, 0), datetime.datetime(2020, 4, 1, 0, 0), datetime.datetime(2020, 5, 1, 0, 0), datetime.datetime(2020, 6, 1, 0, 0), datetime.datetime(2020, 7, 1, 0, 0), datetime.datetime(2020, 8, 1, 0, 0), datetime.datetime(2020, 9, 1, 0, 0), datetime.datetime(2020, 10, 1, 0, 0), datetime.datetime(2020, 11, 1, 0, 0), datetime.datetime(2020, 12, 1, 0, 0)]
[datetime.datetime(2020, 1, 1, 0, 0), datetime.datetime(2020, 2, 1, 0, 0), datetime.datetime(2020, 3, 1, 0, 0), datetime.datetime(2020, 4, 1, 0, 0), datetime.datetime(2020, 5, 1, 0, 0), datetime.datetime(2020, 6, 1, 0, 0), datetime.datetime(2020, 7, 1, 0, 0), datetime.datetime(2020, 8, 1, 0, 0), datetime.datetime(2020, 9, 1, 0, 0), datetime.datetime(2020, 10, 1, 0, 0), datetime.datetime(2020, 11, 1, 0, 0), datetime.datetime(2020, 12, 1, 0, 0)]
[datetime.datetime(2020, 1, 1, 0, 0), datetime.datetime(2020, 2, 1, 0, 0), datetime.datetime(2020, 3, 1, 0, 0), datetime.datetime(2020, 4, 1, 0, 0), datetime.datetime(2020, 5, 1, 0, 0), datetime.datetime(2020, 6, 1, 0, 0), datetime.datetime(2020, 7, 1, 0, 0), datetime.datetime(2020, 8, 1, 0, 0), datetime.datetime(2020, 9, 1, 0, 0), datetime.datetime(2020, 10, 1, 0, 0), datetime.datetime(2020, 11, 1, 0, 0), datetime.datetime(2020, 12, 1, 0, 0)]
[datetime.datetime(2020, 1, 1, 0, 0), datetime.datetime(2020, 2, 1, 0, 0), datetime.datetime(2020, 3, 1, 0, 0), datetime.datetime(2020, 4, 1, 0, 0), datetime.datetime(2020, 5, 1, 0, 0), datetime.datetime(2020, 6, 1, 0, 0), datetime.datetime(2020, 7, 1, 0, 0), datetime.datetime(2020, 8, 1, 0, 0), datetime.datetime(2020, 9, 1, 0, 0), datetime.datetime(2020, 10, 1, 0, 0), datetime.datetime(2020, 11, 1, 0, 0), datetime.datetime(2020, 12, 1, 0, 0)]
[datetime.datetime(2020, 1, 1, 0, 0), datetime.datetime(2020, 2, 1, 0, 0), datetime.datetime(2020, 3, 1, 0, 0), datetime.datetime(2020, 4, 1, 0, 0), datetime.datetime(2020, 5, 1, 0, 0), datetime.datetime(2020, 6, 1, 0, 0), datetime.datetime(2020, 7, 1, 0, 0), datetime.datetime(2020, 8, 1, 0, 0), datetime.datetime(2020, 9, 1, 0, 0), datetime.datetime(2020, 10, 1, 0, 0), datetime.datetime(2020, 11, 1, 0, 0), datetime.datetime(2020, 12, 1, 0, 0)]
[datetime.datetime(2020, 1, 1, 0, 0), datetime.datetime(2020, 2, 1, 0, 0), datetime.datetime(2020, 3, 1, 0, 0), datetime.datetime(2020, 4, 1, 0, 0), datetime.datetime(2020, 5, 1, 0, 0), datetime.datetime(2020, 6, 1, 0, 0), datetime.datetime(2020, 7, 1, 0, 0), datetime.datetime(2020, 8, 1, 0, 0), datetime.datetime(2020, 9, 1, 0, 0), datetime.datetime(2020, 10, 1, 0, 0), datetime.datetime(2020, 11, 1, 0, 0), datetime.datetime(2020, 12, 1, 0, 0)]

In [76]:
df = pd.DataFrame({'A': ['one', 'one', 'two', 'three'] * 6,
                       'B': ['A', 'B', 'C'] * 8,
                       'C': ['foo', 'foo', 'foo', 'bar', 'bar', 'bar'] * 4,
                       'D': np.random.randn(24),
                       'E': np.random.randn(24),
                       'F': [datetime.datetime(2013, i, 1) for i in range(1, 13)]
                       + [datetime.datetime(2013, i, 15) for i in range(1, 13)]})

In [83]:
df

        A  B    C         D         E          F
0     one  A  foo  0.560069  0.856673 2013-01-01
1     one  B  foo -1.063312  0.517660 2013-02-01
2     two  C  foo -1.157855 -0.345534 2013-03-01
3   three  A  bar  1.476665  0.846471 2013-04-01
4     one  B  bar -1.448789  0.843492 2013-05-01
5     one  C  bar  1.036448  0.136018 2013-06-01
6     two  A  foo  2.019587  0.086319 2013-07-01
7   three  B  foo -0.033896 -0.657783 2013-08-01
8     one  C  foo -0.254343 -1.289175 2013-09-01
9     one  A  bar  0.096352 -1.271113 2013-10-01
10    two  B  bar  0.283510 -0.324661 2013-11-01
11  three  C  bar -1.185017 -0.219107 2013-12-01
12    one  A  foo  0.952611 -1.323634 2013-01-15
13    one  B  foo -0.377051  1.608467 2013-02-15
14    two  C  foo  0.899029  0.292491 2013-03-15
15  three  A  bar  1.866612  1.565402 2013-04-15
16    one  B  bar  0.559968 -1.085160 2013-05-15
17    one  C  bar -0.853814 -0.332738 2013-06-15
18    two  A  foo  0.526626  0.432561 2013-07-15
19  three  B  foo  0.644656 -1.683641 2013-08-15
20    one  C  foo -0.657073 -1.523817 2013-09-15
21    one  A  bar -0.131581  0.578298 2013-10-15
22    two  B  bar  0.535272  0.879411 2013-11-15
23  three  C  bar -0.593271 -2.102719 2013-12-15

In [84]:
pd.pivot_table(df, index=['A','B'], values='D', columns=['C'])

C             bar       foo
A     B
one   A -0.017614  0.756340
      B -0.444411 -0.720181
      C  0.091317 -0.455708
three A  1.671638       NaN
      B       NaN  0.305380
      C -0.889144       NaN
two   A       NaN  1.273106
      B  0.409391       NaN
      C       NaN -0.129413

In [88]:
t = pd.pivot_table(df, values='D', index=['B'], columns=['A','C'], aggfunc=np.sum)

In [90]:
print(t.to_string(na_rep=''))

A       one               three                 two
C       bar       foo       bar       foo       bar       foo
B
A -0.035229  1.512680  3.343277                      2.546212
B -0.888821 -1.440363            0.610759  0.818782
C  0.182633 -0.911416 -1.778288                     -0.258826

In [91]:
foo = pd.Categorical(['a','b'], categories=['a','b','c'])

In [92]:
foo

[a, b]
Categories (3, object): [a, b, c]

In [93]:
5//3

1

In [94]:
df10 = pd.DataFrame([{'var1': 'a,b,c', 'var2': 1},
                   {'var1': 'd,e,f', 'var2': 2}])

In [95]:
df10

    var1  var2
0  a,b,c     1
1  d,e,f     2

In [96]:
'a,b,c'.split(',')

['a', 'b', 'c']

In [99]:
df10.assign(var1=df10['var1'].str.split(','))

        var1  var2
0  [a, b, c]     1
1  [d, e, f]     2

In [114]:
s = pd.Series(['a','b','c'], dtype='str')

In [112]:
s

0    a
1    b
2    c
dtype: object

In [105]:
s.astype("str")

0    a
1    b
2    c
dtype: object

In [115]:
print(pd.__version__)

0.25.1

In [116]:
import sys
!conda install --yes --prefix {sys.prefix} pandas

Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: D:\ProgramInUse\Anaconda3

  added / updated specs:
    - pandas


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.8.4                |           py37_0         2.9 MB
    ------------------------------------------------------------
                                           Total:         2.9 MB

The following packages will be UPDATED:

  conda                                        4.8.0-py37_1 --> 4.8.4-py37_0



Downloading and Extracting Packages

conda-4.8.4          | 2.9 MB    |            |   0%
conda-4.8.4          | 2.9 MB    | #7         |  18%
conda-4.8.4          | 2.9 MB    | #####7     |  57%
conda-4.8.4          | 2.9 MB    | #########7 |  97%
conda-4.8.4          | 2.9 MB    | ########## | 100%
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done

In [117]:
print(pd.__version__)

0.25.1

In [120]:
!echo %PATH%

D:\ProgramInUse\Anaconda3;D:\ProgramInUse\Anaconda3\Library\mingw-w64\bin;D:\ProgramInUse\Anaconda3\Library\usr\bin;D:\ProgramInUse\Anaconda3\Library\bin;D:\ProgramInUse\Anaconda3\Scripts;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;D:\ProgramInUse\OracleXE\app\oracle\product\11.2.0\server\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;D:\Java\jdk1.8.0_181\bin;C:\Program Files\PuTTY\;D:\ProgramInUse\Git\cmd;D:\ProgramInUse\python3;D:\ProgramInUse\python3\Scripts;C:\Users\picat\AppData\Local\Microsoft\WindowsApps;D:\ProgramInUse\Microsoft VS Code\bin;C:\Users\picat\AppData\Roaming\Python\Python37\Scripts;C:\Users\picat\AppData\Local\GitHubDesktop\bin

In [127]:
import sys
sys.path

['D:\\',
 'D:\\ProgramInUse\\Anaconda3\\python37.zip',
 'D:\\ProgramInUse\\Anaconda3\\DLLs',
 'D:\\ProgramInUse\\Anaconda3\\lib',
 'D:\\ProgramInUse\\Anaconda3',
 '',
 'C:\\Users\\picat\\AppData\\Roaming\\Python\\Python37\\site-packages',
 'D:\\ProgramInUse\\Anaconda3\\lib\\site-packages',
 'D:\\ProgramInUse\\Anaconda3\\lib\\site-packages\\win32',
 'D:\\ProgramInUse\\Anaconda3\\lib\\site-packages\\win32\\lib',
 'D:\\ProgramInUse\\Anaconda3\\lib\\site-packages\\Pythonwin',
 'D:\\ProgramInUse\\Anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\picat\\.ipython']

In [128]:
pd.__path__

['D:\\ProgramInUse\\Anaconda3\\lib\\site-packages\\pandas']

In [129]:
!conda env list

# conda environments:
#
base                  *  D:\ProgramInUse\Anaconda3
pytorch                  D:\ProgramInUse\Anaconda3\envs\pytorch

In [130]:
sys.executable

'D:\\ProgramInUse\\Anaconda3\\python.exe'

In [131]:
!type python

지정된 파일을 찾을 수 없습니다.

In [132]:
sys.prefix

'D:\\ProgramInUse\\Anaconda3'

In [133]:
!conda update --yes --prefix {sys.prefix} pandas

Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working...

Updating pandas is constricted by

anaconda -> requires pandas==0.25.1=py37ha925a31_0

If you are sure you want an update of your package either try `conda update --all` or install a specific version of the package you want using `conda install <pkg>=<version>`

done

## Package Plan ##

  environment location: D:\ProgramInUse\Anaconda3

  added / updated specs:
    - pandas


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-package-handling-1.6.1|   py37h62dcd97_0         612 KB
    future-0.18.2              |           py37_1         646 KB
    ------------------------------------------------------------
                                           Total:         1.2 MB

The following packages will be UPDATED:

  conda-package-han~                   1.6.0-py37h62dcd97_0 --> 1.6.1-py37h62dcd97_0
  future                                      0.18.2-py37_0 --> 0.18.2-py37_1



Downloading and Extracting Packages

conda-package-handli | 612 KB    |            |   0%
conda-package-handli | 612 KB    | ####1      |  42%
conda-package-handli | 612 KB    | ########## | 100%
conda-package-handli | 612 KB    | ########## | 100%

future-0.18.2        | 646 KB    |            |   0%
future-0.18.2        | 646 KB    | ########## | 100%
future-0.18.2        | 646 KB    | ########## | 100%
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done

In [2]:
import pandas as pd
pd.__version__

'0.25.1'

In [135]:
!python --version

Python 3.7.4

In [136]:
from platform import python_version
print(python_version())

3.7.4

In [137]:
print(sys.version)

3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]

In [4]:
s = pd.Series(["a", None, "b"], dtype="object")

In [5]:
s

0       a
1    None
2       b
dtype: object

In [6]:
"3".isdigit()

True

In [7]:
'a'.isdigit()

False

In [9]:
import numpy as np
s3 = pd.Series(['A','B','C','Abab','Baca','',np.nan,'CABA','dog','cat'])

In [10]:
s3

0       A
1       B
2       C
3    Abab
4    Baca
5
6     NaN
7    CABA
8     dog
9     cat
dtype: object

In [12]:

s3.str.replace('^.a|dog','XX',case=False)

0       A
1       B
2       C
3    Abab
4    XXca
5
6     NaN
7    XXBA
8      XX
9     XXt
dtype: object

In [21]:
"abcdefg"[5::-2]

'fdb'

In [22]:
s3

0       A
1       B
2       C
3    Abab
4    Baca
5
6     NaN
7    CABA
8     dog
9     cat
dtype: object

In [23]:
s3.str.cat(sep=',')

'A,B,C,Abab,Baca,,CABA,dog,cat'

In [24]:
s3.str

In [25]:
s=pd.Series(['a','b','c','d'])
t=pd.Series(['a','b',np.nan,'d'])

In [32]:
d=pd.concat([s,t],axis=0)

In [33]:
d

0      a
1      b
2      c
3      d
0      a
1      b
2    NaN
3      d
dtype: object

In [34]:
u=pd.Series(['b','d','a','c'],index=[1,3,0,2])

In [35]:
u

1    b
3    d
0    a
2    c
dtype: object

In [36]:
u.to_numpy()

array(['b', 'd', 'a', 'c'], dtype=object)

In [37]:
[u,u.to_numpy()]

[1    b
 3    d
 0    a
 2    c
 dtype: object, array(['b', 'd', 'a', 'c'], dtype=object)]

In [46]:
s.str.cat([u,u.to_numpy()], join='left')

0    aab
1    bbd
2    cca
3    ddc
dtype: object

In [52]:
s.str[0][0]

'a'

In [56]:
list(np.random.randint(2,size=20))

[0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0]

In [61]:
["2020{:02}".format(i) for i in range(1,5)]*5

['202001',
 '202002',
 '202003',
 '202004',
 '202001',
 '202002',
 '202003',
 '202004',
 '202001',
 '202002',
 '202003',
 '202004',
 '202001',
 '202002',
 '202003',
 '202004',
 '202001',
 '202002',
 '202003',
 '202004']

In [68]:
df=pd.DataFrame({'a':list(np.random.randint(2,size=12)), 'b':["2020{:02}".format(i) for i in range(1,13)]})

In [69]:
df.sort_values('b')

    a       b
0   0  202001
1   0  202002
2   1  202003
3   1  202004
4   1  202005
5   0  202006
6   0  202007
7   0  202008
8   0  202009
9   0  202010
10  0  202011
11  0  202012

In [70]:
for i in range(1,len(df.index)):
    df.loc[i,'c'] = df.loc[i-1,'a']

In [71]:
df

    a       b    c
0   0  202001  NaN
1   0  202002  0.0
2   1  202003  0.0
3   1  202004  1.0
4   1  202005  1.0
5   0  202006  1.0
6   0  202007  0.0
7   0  202008  0.0
8   0  202009  0.0
9   0  202010  0.0
10  0  202011  0.0
11  0  202012  0.0

In [93]:
df = df.append(df).reset_index()

In [95]:
df['name']=list('h'*12+'j'*12+'k'*12+'l'*12)

In [97]:
df.drop(columns=['c','d'], inplace=True)

In [100]:
df.drop(columns='index', inplace=True)

In [104]:
df.rename(columns={'b':'yyyymm'}, inplace=True)

In [116]:
def myf(x):
    y = x.sort_values(by='yyyymm', ascending=False).reset_index(drop=True)
    for i in range(1,len(y.index)):
        y.loc[i,'b'] = y.loc[i-1,'a']
    print(y)
    return y

df.groupby('name').apply(myf).reset_index(drop=True)

    a  yyyymm name    b
0   0  202012    h  NaN
1   0  202011    h  0.0
2   0  202010    h  0.0
3   0  202009    h  0.0
4   0  202008    h  0.0
5   0  202007    h  0.0
6   0  202006    h  0.0
7   1  202005    h  0.0
8   1  202004    h  1.0
9   1  202003    h  1.0
10  0  202002    h  1.0
11  0  202001    h  0.0
    a  yyyymm name    b
0   0  202012    j  NaN
1   0  202011    j  0.0
2   0  202010    j  0.0
3   0  202009    j  0.0
4   0  202008    j  0.0
5   0  202007    j  0.0
6   0  202006    j  0.0
7   1  202005    j  0.0
8   1  202004    j  1.0
9   1  202003    j  1.0
10  0  202002    j  1.0
11  0  202001    j  0.0
    a  yyyymm name    b
0   0  202012    k  NaN
1   0  202011    k  0.0
2   0  202010    k  0.0
3   0  202009    k  0.0
4   0  202008    k  0.0
5   0  202007    k  0.0
6   0  202006    k  0.0
7   1  202005    k  0.0
8   1  202004    k  1.0
9   1  202003    k  1.0
10  0  202002    k  1.0
11  0  202001    k  0.0
    a  yyyymm name    b
0   0  202012    l  NaN
1   0  202011    l  0.0
2   0  202010    l  0.0
3   0  202009    l  0.0
4   0  202008    l  0.0
5   0  202007    l  0.0
6   0  202006    l  0.0
7   1  202005    l  0.0
8   1  202004    l  1.0
9   1  202003    l  1.0
10  0  202002    l  1.0
11  0  202001    l  0.0

    a  yyyymm name    b
0   0  202012    h  NaN
1   0  202011    h  0.0
2   0  202010    h  0.0
3   0  202009    h  0.0
4   0  202008    h  0.0
5   0  202007    h  0.0
6   0  202006    h  0.0
7   1  202005    h  0.0
8   1  202004    h  1.0
9   1  202003    h  1.0
10  0  202002    h  1.0
11  0  202001    h  0.0
12  0  202012    j  NaN
13  0  202011    j  0.0
14  0  202010    j  0.0
15  0  202009    j  0.0
16  0  202008    j  0.0
17  0  202007    j  0.0
18  0  202006    j  0.0
19  1  202005    j  0.0
20  1  202004    j  1.0
21  1  202003    j  1.0
22  0  202002    j  1.0
23  0  202001    j  0.0
24  0  202012    k  NaN
25  0  202011    k  0.0
26  0  202010    k  0.0
27  0  202009    k  0.0
28  0  202008    k  0.0
29  0  202007    k  0.0
30  0  202006    k  0.0
31  1  202005    k  0.0
32  1  202004    k  1.0
33  1  202003    k  1.0
34  0  202002    k  1.0
35  0  202001    k  0.0
36  0  202012    l  NaN
37  0  202011    l  0.0
38  0  202010    l  0.0
39  0  202009    l  0.0
40  0  202008    l  0.0
41  0  202007    l  0.0
42  0  202006    l  0.0
43  1  202005    l  0.0
44  1  202004    l  1.0
45  1  202003    l  1.0
46  0  202002    l  1.0
47  0  202001    l  0.0

In [119]:
df['b'] = df.groupby('name')['a'].shift(1)

In [120]:
df

    a  yyyymm name    b
0   0  202001    h  NaN
1   0  202002    h  0.0
2   1  202003    h  0.0
3   1  202004    h  1.0
4   1  202005    h  1.0
5   0  202006    h  1.0
6   0  202007    h  0.0
7   0  202008    h  0.0
8   0  202009    h  0.0
9   0  202010    h  0.0
10  0  202011    h  0.0
11  0  202012    h  0.0
12  0  202001    j  NaN
13  0  202002    j  0.0
14  1  202003    j  0.0
15  1  202004    j  1.0
16  1  202005    j  1.0
17  0  202006    j  1.0
18  0  202007    j  0.0
19  0  202008    j  0.0
20  0  202009    j  0.0
21  0  202010    j  0.0
22  0  202011    j  0.0
23  0  202012    j  0.0
24  0  202001    k  NaN
25  0  202002    k  0.0
26  1  202003    k  0.0
27  1  202004    k  1.0
28  1  202005    k  1.0
29  0  202006    k  1.0
30  0  202007    k  0.0
31  0  202008    k  0.0
32  0  202009    k  0.0
33  0  202010    k  0.0
34  0  202011    k  0.0
35  0  202012    k  0.0
36  0  202001    l  NaN
37  0  202002    l  0.0
38  1  202003    l  0.0
39  1  202004    l  1.0
40  1  202005    l  1.0
41  0  202006    l  1.0
42  0  202007    l  0.0
43  0  202008    l  0.0
44  0  202009    l  0.0
45  0  202010    l  0.0
46  0  202011    l  0.0
47  0  202012    l  0.0

In [127]:
from urllib import parse
url = 'https://localhost:8089/servicesNS/nobody/test/storage/collections/data/kvstorecoll'
param = 'query=\{\"$and\":\[\{\"std":{"$gt":4}},{"id":{"$lt":11}}]}'
param_enc = parse.quote(param)
print(param_enc)
param_dec = parse.unquote(param_enc)
print(param_dec)

query%3D%5C%7B%22%24and%22%3A%5C%5B%5C%7B%22std%22%3A%7B%22%24gt%22%3A4%7D%7D%2C%7B%22id%22%3A%7B%22%24lt%22%3A11%7D%7D%5D%7D
query=\{"$and":\[\{"std":{"$gt":4}},{"id":{"$lt":11}}]}

In [128]:
sample = "%7B%20%22%"
print(parse.unquote(sample))

{ "%

In [132]:
import json
with open("D:\\myProjects\\Python\\src\\hello\\testjson.json") as j:
    jt = json.load(j)
jt

{'a': 'ksun', 'b': [1, 2, 3, 4]}

In [135]:
type(jt['a'])

str

In [140]:
jt.keys()

dict_keys(['a', 'b'])

In [141]:
df

    a  yyyymm name    b
0   0  202001    h  NaN
1   0  202002    h  0.0
2   1  202003    h  0.0
3   1  202004    h  1.0
4   1  202005    h  1.0
5   0  202006    h  1.0
6   0  202007    h  0.0
7   0  202008    h  0.0
8   0  202009    h  0.0
9   0  202010    h  0.0
10  0  202011    h  0.0
11  0  202012    h  0.0
12  0  202001    j  NaN
13  0  202002    j  0.0
14  1  202003    j  0.0
15  1  202004    j  1.0
16  1  202005    j  1.0
17  0  202006    j  1.0
18  0  202007    j  0.0
19  0  202008    j  0.0
20  0  202009    j  0.0
21  0  202010    j  0.0
22  0  202011    j  0.0
23  0  202012    j  0.0
24  0  202001    k  NaN
25  0  202002    k  0.0
26  1  202003    k  0.0
27  1  202004    k  1.0
28  1  202005    k  1.0
29  0  202006    k  1.0
30  0  202007    k  0.0
31  0  202008    k  0.0
32  0  202009    k  0.0
33  0  202010    k  0.0
34  0  202011    k  0.0
35  0  202012    k  0.0
36  0  202001    l  NaN
37  0  202002    l  0.0
38  1  202003    l  0.0
39  1  202004    l  1.0
40  1  202005    l  1.0
41  0  202006    l  1.0
42  0  202007    l  0.0
43  0  202008    l  0.0
44  0  202009    l  0.0
45  0  202010    l  0.0
46  0  202011    l  0.0
47  0  202012    l  0.0

In [142]:
df1 = df[['a','yyyymm','name']]

In [144]:
id(df1)

2349521325640

In [145]:
id(df)

2349515572552

In [146]:
df1=pd.DataFrame([[1,202101,0,'m'],[1,202102,1,'m']], columns=['a','yyyymm','b','name'])

In [147]:
df1

   a  yyyymm  b name
0  1  202101  0    m
1  1  202102  1    m

In [167]:
df2 = df.append(df1, sort=False)

In [168]:

print(id(df),id(df1),id(df2),id(df3))

2349515572552 2349521292552 2349516705928 2349516759112

In [155]:
df2.loc[5,'a'] = 1

In [176]:
df3.drop(columns=['name'], inplace=True)

In [177]:
print(id(df3), id(df4))

2349516759112 2349521389576

In [186]:
import json
with open("D:\\myProjects\\Python\\src\\hello\\testjson.json") as j:
    jt = json.load(j)
jt

{'Item': {'spl': '|loadjob abab | where baba| table a,b,l,m,n',
  'filter_col': ['a', 'b', 'l', 'm']},
 'Item1': {'spl': '|loadjob abab | where baba| table a,b,c,d',
  'join': {'Item': {'key': ['a', 'b'], 'outcol': ['c']},
   'Item2': {'key': ['a', 'b']}}}}

In [210]:
it2 = jt['Item1']['join']['Item2']
it2

{'key': ['a', 'b']}

In [215]:
it2.get('outcol') is None

True

In [199]:
df5 = df4[['yyyymm','a']].copy()

In [200]:
print(id(df5), id(df4))

2349521576136 2349521389576

In [214]:
d

    yyyymm  a
0   202001  0
1   202002  0
2   202003  1
3   202004  1
4   202005  1
5   202006  1
6   202007  1
7   202008  0
8   202009  0
9   202010  0
10  202011  0
11  202012  0
12  202001  0
13  202002  0
14  202003  1
15  202004  1
16  202005  1
17  202006  0
18  202007  0
19  202008  0
20  202009  0
21  202010  0
22  202011  0
23  202012  0
24  202001  0
25  202002  0
26  202003  1
27  202004  1
28  202005  1
29  202006  0
30  202007  0
31  202008  0
32  202009  0
33  202010  0
34  202011  0
35  202012  0
36  202001  0
37  202002  0
38  202003  1
39  202004  1
40  202005  1
41  202006  0
42  202007  0
43  202008  0
44  202009  0
45  202010  0
46  202011  0
47  202012  0
0   202101  1
1   202102  1

In [202]:
df5.loc[6,'a'] = 1

In [203]:
df5

    yyyymm  a
0   202001  0
1   202002  0
2   202003  1
3   202004  1
4   202005  1
5   202006  1
6   202007  1
7   202008  0
8   202009  0
9   202010  0
10  202011  0
11  202012  0
12  202001  0
13  202002  0
14  202003  1
15  202004  1
16  202005  1
17  202006  0
18  202007  0
19  202008  0
20  202009  0
21  202010  0
22  202011  0
23  202012  0
24  202001  0
25  202002  0
26  202003  1
27  202004  1
28  202005  1
29  202006  0
30  202007  0
31  202008  0
32  202009  0
33  202010  0
34  202011  0
35  202012  0
36  202001  0
37  202002  0
38  202003  1
39  202004  1
40  202005  1
41  202006  0
42  202007  0
43  202008  0
44  202009  0
45  202010  0
46  202011  0
47  202012  0
0   202101  1
1   202102  1

In [205]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [206]:
import numpy as np
np.random.rand(20,4)

array([[0.8057248 , 0.969451  , 0.757885  , 0.94904429],
       [0.42716064, 0.79964768, 0.5362335 , 0.57866071],
       [0.33161971, 0.16655235, 0.85469008, 0.88602632],
       [0.85492072, 0.04285298, 0.9518084 , 0.71464755],
       [0.34884391, 0.41712814, 0.52007325, 0.16133183],
       [0.28188593, 0.97140499, 0.08169079, 0.70823648],
       [0.0079538 , 0.01531123, 0.27456044, 0.24616821],
       [0.76852567, 0.92617844, 0.54028468, 0.02959948],
       [0.3712274 , 0.86992775, 0.79119981, 0.06449397],
       [0.92666948, 0.94571846, 0.21528307, 0.72977848],
       [0.92256481, 0.34346669, 0.46969979, 0.24486191],
       [0.84542873, 0.02566744, 0.77705633, 0.46208992],
       [0.2138694 , 0.69607396, 0.37409066, 0.86412834],
       [0.25863933, 0.43111736, 0.42353258, 0.0969069 ],
       [0.32622087, 0.256917  , 0.4513107 , 0.79815692],
       [0.80046554, 0.0649847 , 0.50934645, 0.42988292],
       [0.52816576, 0.45596171, 0.45278615, 0.06633383],
       [0.50905495, 0.96482713, 0.23637194, 0.42418821],
       [0.96612427, 0.36686979, 0.92269524, 0.31451799],
       [0.69417953, 0.70280633, 0.60091664, 0.54544982]])

In [207]:
dflookup = pd.DataFrame(np.random.rand(20, 4), columns = ['A', 'B', 'C', 'D'])

In [208]:
dflookup

           A         B         C         D
0   0.507063  0.027134  0.755279  0.523008
1   0.502210  0.642478  0.640161  0.023263
2   0.230107  0.301833  0.497366  0.131660
3   0.051724  0.674235  0.697777  0.797534
4   0.729386  0.135173  0.672618  0.741961
5   0.566604  0.222948  0.076319  0.994165
6   0.991778  0.067282  0.850216  0.925763
7   0.933478  0.926538  0.276275  0.517130
8   0.516409  0.416875  0.115150  0.613556
9   0.424272  0.043980  0.767809  0.777872
10  0.731419  0.482852  0.359518  0.541430
11  0.653291  0.795271  0.700282  0.579923
12  0.875223  0.113133  0.976730  0.127578
13  0.733573  0.681545  0.037205  0.439191
14  0.616621  0.236713  0.096839  0.902737
15  0.272910  0.857071  0.536581  0.154991
16  0.897418  0.260247  0.939600  0.177919
17  0.816735  0.972747  0.836734  0.839760
18  0.971040  0.906013  0.407906  0.765199
19  0.304133  0.868647  0.971819  0.493174

In [209]:
dflookup.lookup(list(range(0, 10, 2)), ['B', 'C', 'A', 'B', 'D'])

array([0.02713383, 0.49736569, 0.72938556, 0.06728156, 0.61355628])

In [216]:
%history

pd.__version__
import pandas as pd
pd.__version__
s = pd.Series(["a", None, "b"], dtype="string")
s = pd.Series(["a", None, "b"], dtype="object")
s
"3".isdigit()
'a'.isdigit()
s3 = pd.Series(['A','B','C','Abab','Baca','',np.nan,'CABA','dog','cat'])
import numpy as np
s3 = pd.Series(['A','B','C','Abab','Baca','',np.nan,'CABA','dog','cat'])
s3
s3.str.replace('^.a')

s3.str.replace('^.a|dog','XX',case=False)
"abcdefg"[0:6:2]
"abcdefg"[0:6:-1]
"abcdefg"[::-1]
"abcdefg"[7:0:-1]
"abcdefg"[4:0:-1]
"abcdefg"[6:0:-2]
"abcdefg"[6::-2]
"abcdefg"[6:-1:-2]
"abcdefg"[5::-2]
s3
s3.str.cat(sep=',')
s3.str
s=pd.Series(['a','b','c','d'])
t=pd.Series(['a','b',np.nan,'d'])
d=pd.concat([s,t],axis=1)
d
d=pd.concat([s,t],axis=0)
d
d=pd.concat([s,t],axis=1)
d
d=pd.concat([s,t],axis=0)
d
u=pd.Series(['b','d','a','c'],index=[1,3,0,2])
u
u.to_numpy()
[u,u.to_numpy()]
u.str.to_list()
u.str.tolist()
u.str
[u.str]
u.str()
u.str.cat(u.to_numpy())
s.str.cat([u,u.to_numpy()], join='left')
s.str.cat([u,u.to_numpy()])
s.str.cat([u,u.to_numpy()], join='left')
s.str[0]
s.str[1]
s.str[2]
s.str[0]
s.str.loc[0,0]
s.str[0][0]
df
np.random.randn(20,size=2)
np.random.randint(2,size=20)
list(np.random.randint(2,size=20))
"2020{:02}".format(2)
"2020{:02}".format(11)
["2020{:02}".format(i) for i in range(4)]
["2020{:02}".format(i) for i in range(1,5)]
["2020{:02}".format(i) for i in range(1,5)]*5
df=pd.DataFrame({'a':list(np.random.randint(2,size=20)), 'b':["2020{:02}".format(i) for i in range(1,5)]*5})
df=pd.DataFrame({'a':list(np.random.randint(2,size=20)), 'b':["2020{:02}".format(i) for i in range(1,5)]*5})
df
df.sort('b')
df.sort_value('b')
df.sort_values('b')
df=pd.DataFrame({'a':list(np.random.randint(2,size=12)), 'b':["2020{:02}".format(i) for i in range(1,13)]})
df.sort_values('b')
for i in range(1,len(df.index)):
    df.loc[i,'c'] = df.loc[i-1,'a']
df
df['d'] = df['a']==df['c']
df
df['c']==np.nan
df['c'] is np.nan
df['c'] == np.nan
df['c'].isnull()
df = df.append(df)
df
df = df.append(df, ignore_idex=True)
df.append(df).reset_index()
('a1'*12+'b1'*12+'c1'*12+'d1'*12).tolist()
('a1'*12+'b1'*12+'c1'*12+'d1'*12).list()
('a1'*12+'b1'*12+'c1'*12+'d1'*12)
[('a1'*12+'b1'*12+'c1'*12+'d1'*12)]
['a1'*12+'b1'*12+'c1'*12+'d1'*12]
['a'*12+'b'*12+'c'*12+'d'*12]
list('a'*12+'b'*12+'c'*12+'d'*12)
list('h'*12+'j'*12+'k'*12+'l'*12)
df['name'] = list('h'*12+'j'*12+'k'*12+'l'*12)
len(list('h'*12+'j'*12+'k'*12+'l'*12))
len(df.index)
df = df.append(df).reset_index()
df['name'=list('h'*12+'j'*12+'k'*12+'l'*12)
df['name']=list('h'*12+'j'*12+'k'*12+'l'*12)
df.drop(columns='c')
df.drop(columns=['c','d'], inplace=True)
df
df.drop(columns='index')
df.drop(columns='index', inplace=True)
df
df.rename({'b':'yyyymm'})
df.rename(columns={'b':'yyyymm'})
df.rename(columns={'b':'yyyymm'}, inplace=True)
df
def myf(x):
    print(x)
    return x['a']

df.groupby('name').apply(myf)
def myf(x):
    x.sort_values(by='yyyymm', ascending=False)
    print(x)
    return x

df.groupby('name').apply(myf)
def myf(x):
    x.sort_values(by='yyyymm', ascending=False, inplace=True)
    print(x)
    return x

df.groupby('name').apply(myf)
df.loc[41,['a','yyyymm']]
df.loc[41,['a','yyyymm','name']]
def myf(x):
    y.sort_values(by='yyyymm', ascending=False).reset_index()
    print(y)
    return y

df.groupby('name').apply(myf)
def myf(x):
    y = x.sort_values(by='yyyymm', ascending=False).reset_index()
    print(y)
    return y

df.groupby('name').apply(myf)
def myf(x):
    y = x.sort_values(by='yyyymm', ascending=False).reset_index(drop=True)
    print(y)
    return y

df.groupby('name').apply(myf)
def myf(x):
    y = x.sort_values(by='yyyymm', ascending=False).reset_index(drop=True)
    print(y)
    return y

df.groupby('name').apply(myf).reset_index(drop=True)
def myf(x):
    y = x.sort_values(by='yyyymm', ascending=False).reset_index(drop=True)
    for i in range(1,len(y.index)):
        y.loc[i,'b'] = y.loc[i-1,'b']
    print(y)
    return y

df.groupby('name').apply(myf).reset_index(drop=True)
def myf(x):
    y = x.sort_values(by='yyyymm', ascending=False).reset_index(drop=True)
    for i in range(1,len(y.index)):
        y.loc[i,'b'] = y.loc[i-1,'a']
    print(y)
    return y

df.groupby('name').apply(myf).reset_index(drop=True)
df
df.groupby('name')['a'].shift(1)
df['b'] = df.groupby('name')['a'].shift(1)
df
from urllib import parse
url = 'https://localhost:8089/servicesNS/nobody/test/storage/collections/data/kvstorecoll'
param = 'query={"$and":[{"std":{"$gt":4}},{"id":{"$lt":11}}]}'
param_enc = param.text(param)
print(param_enc)
from urllib import parse
url = 'https://localhost:8089/servicesNS/nobody/test/storage/collections/data/kvstorecoll'
param = 'query={"$and":[{"std":{"$gt":4}},{"id":{"$lt":11}}]}'
param_enc = parse.text(param)
print(param_enc)
from urllib import parse
url = 'https://localhost:8089/servicesNS/nobody/test/storage/collections/data/kvstorecoll'
param = 'query={"$and":[{"std":{"$gt":4}},{"id":{"$lt":11}}]}'
param_enc = parse.quote(param)
print(param_enc)
from urllib import parse
url = 'https://localhost:8089/servicesNS/nobody/test/storage/collections/data/kvstorecoll'
param = 'query={"$and":[{"std":{"$gt":4}},{"id":{"$lt":11}}]}'
param_enc = parse.quote(param)
print(param_enc)
param_dec = parse.quote(param_enc)
from urllib import parse
url = 'https://localhost:8089/servicesNS/nobody/test/storage/collections/data/kvstorecoll'
param = 'query={"$and":[{"std":{"$gt":4}},{"id":{"$lt":11}}]}'
param_enc = parse.quote(param)
print(param_enc)
param_dec = parse.quote(param_enc)
print(param_dec)
from urllib import parse
url = 'https://localhost:8089/servicesNS/nobody/test/storage/collections/data/kvstorecoll'
param = 'query={"$and":[{"std":{"$gt":4}},{"id":{"$lt":11}}]}'
param_enc = parse.quote(param)
print(param_enc)
param_dec = parse.unquote(param_enc)
print(param_dec)
from urllib import parse
url = 'https://localhost:8089/servicesNS/nobody/test/storage/collections/data/kvstorecoll'
param = 'query=\{\"$and\":\[\{\"std":{"$gt":4}},{"id":{"$lt":11}}]}'
param_enc = parse.quote(param)
print(param_enc)
param_dec = parse.unquote(param_enc)
print(param_dec)
sample = "%7B%20%22%"
print(parse.unquote(sample))
import pandas as pd
tj = pd.read_json("D:\myProjects\Python\src\hello\testjson.json")
tj
import json
with open("D:\myProjects\Python\src\hello\testjson.json") as j:
    jt = json.load(j)
tj
import json
with open("D:\\myProjects\\Python\\src\\hello\\testjson.json") as j:
    jt = json.load(j)
tj
import json
with open("D:\\myProjects\\Python\\src\\hello\\testjson.json") as j:
    jt = json.load(j)
jt
jt['b']
type(jt['b'])
type(jt['a'])
jt.keys
list(jt.keys)
jt.keys.tolist()
jt.keys
jt.keys()
df
df1 = df[['a','yyyymm','name']]
df is df1
id(df1)
id(df)
df1=pd.DataFrame([[1,202101,0,'m'],[1,202102,1,'m']], columns=['a','yyyymm','b','name'])
df1
df2 = df.append(df1)
df2
id(df2)
id(df)
id(df2)
id(df1)

print(id(df),id(df1),id(df2))
df2
df2.loc[5,'a'] = 1
df2
df
df3 = df2
print(id(df2) id(df3))
print(id(df2), id(df3))
print(id(df2) is id(df3))
print(id(df2) == id(df3))
print((df2) is (df3))
print((df2) == (df3))
df2
df3
df2 = df.append(df1, sort=False)

print(id(df),id(df1),id(df2),id(df3))
df2
df3
foo = pd.Categorical(['a', 'b'], categories=['a', 'b', 'c'])
foo
df3
df4 = df3.drop('name')
df4 = df3.drop(columns=['name'])
print(id(df3), id(df4))
df3.drop(columns=['name'], inplace=True)
print(id(df3), id(df4))
import json
with open("D:\\myProjects\\Python\\src\\hello\\testjson.json") as j:
    jt = json.load(j)
jt
jt['Item']['spl']
jt['Item1']['join']['key']
jt['Item1']['join']['Item']['key']
jt['Item1']['join']['Item2']['key']
jt['Item1']['join']['Item3']['key']
import json
with open("D:\\myProjects\\Python\\src\\hello\\testjson.json") as j:
    jt = json.load(j)
jt
jt['Item1']['join']['Item2']['outcol']
import json
with open("D:\\myProjects\\Python\\src\\hello\\testjson.json") as j:
    jt = json.load(j)
jt
jt['Item1']['join']['Item2']['outcol']
'outcol' in jt['Item1']['join']['Item2'].keys()
jt['Item1']['join']['Item2']
df3
df4
df5 = df4[['yyyymm','a']]
print(id(df5), id(df4))
df5
df5.loc[6,'a'] = 1
df5
df4
df5
df5 = df4[['yyyymm','a']].copy()
print(id(df5), id(df4))
df5
df5.loc[6,'a'] = 1
df5
range(0,10,2)
list(range(0,10,2))
import numpy as np
np.random.rand(20,4)
dflookup = pd.DataFrame(np.random.rand(20, 4), columns = ['A', 'B', 'C', 'D'])
dflookup
dflookup.lookup(list(range(0, 10, 2)), ['B', 'C', 'A', 'B', 'D'])
it2 = jt['Item1']['join']['Item2']
it2
it2.get('key')
it2.get('outcol')
it2.get('outcol') == None
df5
it2.get('outcol') is None
%history

In [217]:
df

    a  yyyymm name    b
0   0  202001    h  NaN
1   0  202002    h  0.0
2   1  202003    h  0.0
3   1  202004    h  1.0
4   1  202005    h  1.0
5   0  202006    h  1.0
6   0  202007    h  0.0
7   0  202008    h  0.0
8   0  202009    h  0.0
9   0  202010    h  0.0
10  0  202011    h  0.0
11  0  202012    h  0.0
12  0  202001    j  NaN
13  0  202002    j  0.0
14  1  202003    j  0.0
15  1  202004    j  1.0
16  1  202005    j  1.0
17  0  202006    j  1.0
18  0  202007    j  0.0
19  0  202008    j  0.0
20  0  202009    j  0.0
21  0  202010    j  0.0
22  0  202011    j  0.0
23  0  202012    j  0.0
24  0  202001    k  NaN
25  0  202002    k  0.0
26  1  202003    k  0.0
27  1  202004    k  1.0
28  1  202005    k  1.0
29  0  202006    k  1.0
30  0  202007    k  0.0
31  0  202008    k  0.0
32  0  202009    k  0.0
33  0  202010    k  0.0
34  0  202011    k  0.0
35  0  202012    k  0.0
36  0  202001    l  NaN
37  0  202002    l  0.0
38  1  202003    l  0.0
39  1  202004    l  1.0
40  1  202005    l  1.0
41  0  202006    l  1.0
42  0  202007    l  0.0
43  0  202008    l  0.0
44  0  202009    l  0.0
45  0  202010    l  0.0
46  0  202011    l  0.0
47  0  202012    l  0.0

In [222]:
df.loc[len(df)] = [0,'202101','l',0]

In [231]:
df.iloc[:3]

   a  yyyymm name    b
0  0  202001    h  NaN
1  0  202002    h  0.0
2  1  202003    h  0.0

In [234]:
s = pd.Series(np.arange(4), index=['a','a','b','c'])
s.loc[s.index.intersection(['c','d'])].reindex(['c','d'])

c    3.0
d    NaN
dtype: float64