In [3]:
import pandas as pd

In [ ]:
df1.head

In [ ]:
row_concat=pd.concat([df1,df2,df3])
print(row_concat)

In [ ]:
print(row_concat.loc[[2,3]])

In [ ]:
new_row_df=pd.DataFrame([['n1','n2','n3','n4']], columns=['A','B','C','D'])
print(new_row_df)

In [4]:
gapminder=pd.read_csv('data/gapminder.tsv',sep='\t')

In [6]:
life_exp=gapminder.groupby(['year'])['lifeExp'].mean()
print(life_exp)

year
1952    49.057620
1957    51.507401
1962    53.609249
1967    55.678290
1972    57.647386
1977    59.570157
1982    61.533197
1987    63.212613
1992    64.160338
1997    65.014676
2002    65.694923
2007    67.007423
Name: lifeExp, dtype: float64

In [7]:
print(type(life_exp))

<class 'pandas.core.series.Series'>

In [23]:
y2000=life_exp[life_exp.index > 2000]
print(y2000)

year
2002    65.694923
2007    67.007423
Name: lifeExp, dtype: float64

In [14]:
list(range(2000,2010))

[2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009]

In [24]:
ebola=pd.read_csv('data/country_timeseries.csv')

In [25]:
ebola.head

<bound method NDFrame.head of            Date  Day  Cases_Guinea  Cases_Liberia  Cases_SierraLeone  \
0      1/5/2015  289        2776.0            NaN            10030.0
1      1/4/2015  288        2775.0            NaN             9780.0
2      1/3/2015  287        2769.0         8166.0             9722.0
3      1/2/2015  286           NaN         8157.0                NaN
4    12/31/2014  284        2730.0         8115.0             9633.0
..          ...  ...           ...            ...                ...
117   3/27/2014    5         103.0            8.0                6.0
118   3/26/2014    4          86.0            NaN                NaN
119   3/25/2014    3          86.0            NaN                NaN
120   3/24/2014    2          86.0            NaN                NaN
121   3/22/2014    0          49.0            NaN                NaN

     Cases_Nigeria  Cases_Senegal  Cases_UnitedStates  Cases_Spain  \
0              NaN            NaN                 NaN          NaN
1              NaN            NaN                 NaN          NaN
2              NaN            NaN                 NaN          NaN
3              NaN            NaN                 NaN          NaN
4              NaN            NaN                 NaN          NaN
..             ...            ...                 ...          ...
117            NaN            NaN                 NaN          NaN
118            NaN            NaN                 NaN          NaN
119            NaN            NaN                 NaN          NaN
120            NaN            NaN                 NaN          NaN
121            NaN            NaN                 NaN          NaN

     Cases_Mali  Deaths_Guinea  Deaths_Liberia  Deaths_SierraLeone  \
0           NaN         1786.0             NaN              2977.0
1           NaN         1781.0             NaN              2943.0
2           NaN         1767.0          3496.0              2915.0
3           NaN            NaN          3496.0                 NaN
4           NaN         1739.0          3471.0              2827.0
..          ...            ...             ...                 ...
117         NaN           66.0             6.0                 5.0
118         NaN           62.0             NaN                 NaN
119         NaN           60.0             NaN                 NaN
120         NaN           59.0             NaN                 NaN
121         NaN           29.0             NaN                 NaN

     Deaths_Nigeria  Deaths_Senegal  Deaths_UnitedStates  Deaths_Spain  \
0               NaN             NaN                  NaN           NaN
1               NaN             NaN                  NaN           NaN
2               NaN             NaN                  NaN           NaN
3               NaN             NaN                  NaN           NaN
4               NaN             NaN                  NaN           NaN
..              ...             ...                  ...           ...
117             NaN             NaN                  NaN           NaN
118             NaN             NaN                  NaN           NaN
119             NaN             NaN                  NaN           NaN
120             NaN             NaN                  NaN           NaN
121             NaN             NaN                  NaN           NaN

     Deaths_Mali
0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
..           ...
117          NaN
118          NaN
119          NaN
120          NaN
121          NaN

[122 rows x 18 columns]>

In [27]:
ebola.head(n=10)

,Date,Day,Cases_Guinea,Cases_Liberia,Cases_SierraLeone,Cases_Nigeria,Cases_Senegal,Cases_UnitedStates,Cases_Spain,Cases_Mali,Deaths_Guinea,Deaths_Liberia,Deaths_SierraLeone,Deaths_Nigeria,Deaths_Senegal,Deaths_UnitedStates,Deaths_Spain,Deaths_Mali
0,1/5/2015,289,2776.0,NaN,10030.0,NaN,NaN,NaN,NaN,NaN,1786.0,NaN,2977.0,NaN,NaN,NaN,NaN,NaN
1,1/4/2015,288,2775.0,NaN,9780.0,NaN,NaN,NaN,NaN,NaN,1781.0,NaN,2943.0,NaN,NaN,NaN,NaN,NaN
2,1/3/2015,287,2769.0,8166.0,9722.0,NaN,NaN,NaN,NaN,NaN,1767.0,3496.0,2915.0,NaN,NaN,NaN,NaN,NaN
3,1/2/2015,286,NaN,8157.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3496.0,NaN,NaN,NaN,NaN,NaN,NaN
4,12/31/2014,284,2730.0,8115.0,9633.0,NaN,NaN,NaN,NaN,NaN,1739.0,3471.0,2827.0,NaN,NaN,NaN,NaN,NaN
5,12/28/2014,281,2706.0,8018.0,9446.0,NaN,NaN,NaN,NaN,NaN,1708.0,3423.0,2758.0,NaN,NaN,NaN,NaN,NaN
6,12/27/2014,280,2695.0,NaN,9409.0,NaN,NaN,NaN,NaN,NaN,1697.0,NaN,2732.0,NaN,NaN,NaN,NaN,NaN
7,12/24/2014,277,2630.0,7977.0,9203.0,NaN,NaN,NaN,NaN,NaN,NaN,3413.0,2655.0,NaN,NaN,NaN,NaN,NaN
8,12/21/2014,273,2597.0,NaN,9004.0,NaN,NaN,NaN,NaN,NaN,1607.0,NaN,2582.0,NaN,NaN,NaN,NaN,NaN
9,12/20/2014,272,2571.0,7862.0,8939.0,NaN,NaN,NaN,NaN,NaN,1586.0,3384.0,2556.0,NaN,NaN,NaN,NaN,NaN

In [29]:
ebola.shape

(122, 18)

In [31]:
ebola.count()

Date                   122
Day                    122
Cases_Guinea            93
Cases_Liberia           83
Cases_SierraLeone       87
Cases_Nigeria           38
Cases_Senegal           25
Cases_UnitedStates      18
Cases_Spain             16
Cases_Mali              12
Deaths_Guinea           92
Deaths_Liberia          81
Deaths_SierraLeone      87
Deaths_Nigeria          38
Deaths_Senegal          22
Deaths_UnitedStates     18
Deaths_Spain            16
Deaths_Mali             12
dtype: int64

In [34]:
ebola.count() - ebola.shape[0]

Date                     0
Day                      0
Cases_Guinea           -29
Cases_Liberia          -39
Cases_SierraLeone      -35
Cases_Nigeria          -84
Cases_Senegal          -97
Cases_UnitedStates    -104
Cases_Spain           -106
Cases_Mali            -110
Deaths_Guinea          -30
Deaths_Liberia         -41
Deaths_SierraLeone     -35
Deaths_Nigeria         -84
Deaths_Senegal        -100
Deaths_UnitedStates   -104
Deaths_Spain          -106
Deaths_Mali           -110
dtype: int64

In [41]:
ebola.interpolate().head()

,Date,Day,Cases_Guinea,Cases_Liberia,Cases_SierraLeone,Cases_Nigeria,Cases_Senegal,Cases_UnitedStates,Cases_Spain,Cases_Mali,Deaths_Guinea,Deaths_Liberia,Deaths_SierraLeone,Deaths_Nigeria,Deaths_Senegal,Deaths_UnitedStates,Deaths_Spain,Deaths_Mali
0,1/5/2015,289,2776.0,NaN,10030.0,NaN,NaN,NaN,NaN,NaN,1786.0,NaN,2977.0,NaN,NaN,NaN,NaN,NaN
1,1/4/2015,288,2775.0,NaN,9780.0,NaN,NaN,NaN,NaN,NaN,1781.0,NaN,2943.0,NaN,NaN,NaN,NaN,NaN
2,1/3/2015,287,2769.0,8166.0,9722.0,NaN,NaN,NaN,NaN,NaN,1767.0,3496.0,2915.0,NaN,NaN,NaN,NaN,NaN
3,1/2/2015,286,2749.5,8157.0,9677.5,NaN,NaN,NaN,NaN,NaN,1753.0,3496.0,2871.0,NaN,NaN,NaN,NaN,NaN
4,12/31/2014,284,2730.0,8115.0,9633.0,NaN,NaN,NaN,NaN,NaN,1739.0,3471.0,2827.0,NaN,NaN,NaN,NaN,NaN

In [43]:
ebola.index

RangeIndex(start=0, stop=122, step=1)

In [44]:
print(ebola.columns)

Index(['Date', 'Day', 'Cases_Guinea', 'Cases_Liberia', 'Cases_SierraLeone',
       'Cases_Nigeria', 'Cases_Senegal', 'Cases_UnitedStates', 'Cases_Spain',
       'Cases_Mali', 'Deaths_Guinea', 'Deaths_Liberia', 'Deaths_SierraLeone',
       'Deaths_Nigeria', 'Deaths_Senegal', 'Deaths_UnitedStates',
       'Deaths_Spain', 'Deaths_Mali'],
      dtype='object')

In [45]:
ebola_long=pd.melt(ebola, id_vars=['Date','Day'])

In [46]:
print(ebola_long)

            Date  Day      variable   value
0       1/5/2015  289  Cases_Guinea  2776.0
1       1/4/2015  288  Cases_Guinea  2775.0
2       1/3/2015  287  Cases_Guinea  2769.0
3       1/2/2015  286  Cases_Guinea     NaN
4     12/31/2014  284  Cases_Guinea  2730.0
...          ...  ...           ...     ...
1947   3/27/2014    5   Deaths_Mali     NaN
1948   3/26/2014    4   Deaths_Mali     NaN
1949   3/25/2014    3   Deaths_Mali     NaN
1950   3/24/2014    2   Deaths_Mali     NaN
1951   3/22/2014    0   Deaths_Mali     NaN

[1952 rows x 4 columns]

In [50]:
ebola_long.variable

0       Cases_Guinea
1       Cases_Guinea
2       Cases_Guinea
3       Cases_Guinea
4       Cases_Guinea
            ...
1947     Deaths_Mali
1948     Deaths_Mali
1949     Deaths_Mali
1950     Deaths_Mali
1951     Deaths_Mali
Name: variable, Length: 1952, dtype: object

In [52]:
import os
import urllib.request
with open('data/raw_data_urls.txt','r') as data_urls:
    for line, url in enumerate(data_urls):
        if line == 5:
            break
        fn = url.split('/')[-1].strip()
        fp = os.path.join('','data',fn)
        print(url)
        print(fp)

https://s3.amazonaws.com/nyc-tlc/trip+data/fhv_tripdata_2015-01.csv

data\fhv_tripdata_2015-01.csv
https://s3.amazonaws.com/nyc-tlc/trip+data/fhv_tripdata_2015-02.csv

data\fhv_tripdata_2015-02.csv
https://s3.amazonaws.com/nyc-tlc/trip+data/fhv_tripdata_2015-03.csv

data\fhv_tripdata_2015-03.csv
https://s3.amazonaws.com/nyc-tlc/trip+data/fhv_tripdata_2015-04.csv

data\fhv_tripdata_2015-04.csv
https://s3.amazonaws.com/nyc-tlc/trip+data/fhv_tripdata_2015-05.csv

data\fhv_tripdata_2015-05.csv

In [54]:
"3,4".partition(',')

('3', ',', '4')

In [60]:
print("My ID:{0:5d}".format(42))

My ID:   42

In [65]:
! ipconfig

Windows IP 구성


이더넷 어댑터 이더넷:

   미디어 상태 . . . . . . . . : 미디어 연결 끊김
   연결별 DNS 접미사. . . . :

무선 LAN 어댑터 로컬 영역 연결* 2:

   미디어 상태 . . . . . . . . : 미디어 연결 끊김
   연결별 DNS 접미사. . . . :

무선 LAN 어댑터 로컬 영역 연결* 1:

   미디어 상태 . . . . . . . . : 미디어 연결 끊김
   연결별 DNS 접미사. . . . :

이더넷 어댑터 VMware Network Adapter VMnet1:

   연결별 DNS 접미사. . . . :
   링크-로컬 IPv6 주소 . . . . : fe80::4dc2:c6a6:4c71:8d0b%9
   IPv4 주소 . . . . . . . . . : 192.168.192.1
   서브넷 마스크 . . . . . . . : 255.255.255.0
   기본 게이트웨이 . . . . . . :

이더넷 어댑터 VMware Network Adapter VMnet8:

   연결별 DNS 접미사. . . . :
   링크-로컬 IPv6 주소 . . . . : fe80::350f:db8b:69a8:8317%5
   IPv4 주소 . . . . . . . . . : 192.168.111.1
   서브넷 마스크 . . . . . . . : 255.255.255.0
   기본 게이트웨이 . . . . . . :

무선 LAN 어댑터 Wi-Fi:

   연결별 DNS 접미사. . . . :
   링크-로컬 IPv6 주소 . . . . : fe80::b918:ac31:4a4f:f964%11
   IPv4 주소 . . . . . . . . . : 172.30.27.62
   서브넷 마스크 . . . . . . . : 255.240.0.0
   기본 게이트웨이 . . . . . . : 172.30.1.254

이더넷 어댑터 Bluetooth 네트워크 연결 3:

   미디어 상태 . . . . . . . . : 미디어 연결 끊김
   연결별 DNS 접미사. . . . :

In [66]:
%%cmd
ipconfig

Microsoft Windows [Version 10.0.18362.592]
(c) 2019 Microsoft Corporation. All rights reserved.

D:\myProjects\pandas>ipconfig

Windows IP 구성


이더넷 어댑터 이더넷:

   미디어 상태 . . . . . . . . : 미디어 연결 끊김
   연결별 DNS 접미사. . . . :

무선 LAN 어댑터 로컬 영역 연결* 2:

   미디어 상태 . . . . . . . . : 미디어 연결 끊김
   연결별 DNS 접미사. . . . :

무선 LAN 어댑터 로컬 영역 연결* 1:

   미디어 상태 . . . . . . . . : 미디어 연결 끊김
   연결별 DNS 접미사. . . . :

이더넷 어댑터 VMware Network Adapter VMnet1:

   연결별 DNS 접미사. . . . :
   링크-로컬 IPv6 주소 . . . . : fe80::4dc2:c6a6:4c71:8d0b%9
   IPv4 주소 . . . . . . . . . : 192.168.192.1
   서브넷 마스크 . . . . . . . : 255.255.255.0
   기본 게이트웨이 . . . . . . :

이더넷 어댑터 VMware Network Adapter VMnet8:

   연결별 DNS 접미사. . . . :
   링크-로컬 IPv6 주소 . . . . : fe80::350f:db8b:69a8:8317%5
   IPv4 주소 . . . . . . . . . : 192.168.111.1
   서브넷 마스크 . . . . . . . : 255.255.255.0
   기본 게이트웨이 . . . . . . :

무선 LAN 어댑터 Wi-Fi:

   연결별 DNS 접미사. . . . :
   링크-로컬 IPv6 주소 . . . . : fe80::b918:ac31:4a4f:f964%11
   IPv4 주소 . . . . . . . . . : 172.30.27.62
   서브넷 마스크 . . . . . . . : 255.240.0.0
   기본 게이트웨이 . . . . . . : 172.30.1.254

이더넷 어댑터 Bluetooth 네트워크 연결 3:

   미디어 상태 . . . . . . . . : 미디어 연결 끊김
   연결별 DNS 접미사. . . . :

D:\myProjects\pandas>

In [67]:
pwd

'D:\\myProjects\\pandas'

In [68]:
vector_list=[[1,2,3]]

In [70]:
print(vector_list*3)

[[1, 2, 3], [1, 2, 3], [1, 2, 3]]

In [71]:
numbers=[1,2,3,4,5,6]
*a,=numbers

In [72]:
type(a)

list

In [74]:
print(a)

[1, 2, 3, 4, 5, 6]

In [83]:
from functools import reduce
primes=[2,3,5,7,11,13]
def myproduct(numbers):
    print(numbers[0], numbers[1])
    p = reduce(lambda x,y:x*y, numbers)
    return p

myproduct(primes)

2 3

30030

In [87]:
gen = (x**2 for x in range(10))
list(gen)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [88]:
from platform import python_version

print(python_version())

3.7.4

In [94]:
sumvalue=reduce(lambda x,y:x+y, range(5))
print(sumvalue)

10

In [95]:
print(range(10))

range(0, 10)

In [96]:
from concurrent.futures import ProcessPoolExecutor
from time import sleep
 
def return_after_5_secs(message):
    sleep(5)
    return message
 
pool = ProcessPoolExecutor(3)
 
future = pool.submit(return_after_5_secs, ("hello"))
print(future.done())
sleep(5)
print(future.done())
print("Result: " + future.result())

False
True

BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

In [99]:
URLS=['abc','def','ghi']
tt={'a'+url : url for url in URLS}
tt

{'aabc': 'abc', 'adef': 'def', 'aghi': 'ghi'}

In [98]:
import concurrent.futures
import urllib.request
 
URLS = ['http://www.foxnews.com/',
        'http://www.cnn.com/',
        'http://europe.wsj.com/',
        'http://www.bbc.co.uk/',
        'http://some-made-up-domain.com/']
 

def load_url(url, timeout):
    with urllib.request.urlopen(url, timeout=timeout) as conn:
        return conn.read()
 

with concurrent.futures.ThreadPoolExecutor(max_workers=5) as executor:
    
    future_to_url = {executor.submit(load_url, url, 60): url for url in URLS}
    print(future_to_url)
    for future in concurrent.futures.as_completed(future_to_url):
        url = future_to_url[future]
        try:
            data = future.result()
        except Exception as exc:
            print('%r generated an exception: %s' % (url, exc))
        else:
            print('%r page is %d bytes' % (url, len(data)))

{<Future at 0x2aa81582908 state=running>: 'http://www.foxnews.com/', <Future at 0x2aa8157d148 state=running>: 'http://www.cnn.com/', <Future at 0x2aa81586a48 state=running>: 'http://europe.wsj.com/', <Future at 0x2aa8158f488 state=running>: 'http://www.bbc.co.uk/', <Future at 0x2aa8158fd48 state=running>: 'http://some-made-up-domain.com/'}
'http://some-made-up-domain.com/' generated an exception: <urlopen error [Errno 11001] getaddrinfo failed>
'http://www.foxnews.com/' page is 224483 bytes
'http://www.cnn.com/' page is 1169959 bytes
'http://europe.wsj.com/' page is 2896343 bytes
'http://www.bbc.co.uk/' page is 251007 bytes

In [106]:
import concurrent.futures
import math

PRIMES = [
    112272535095293,
    112582705942171,
    112272535095293,
    115280095190773,
    115797848077099,
    1099726899285419]

def is_prime(n):
    if n < 2:
        return False
    if n == 2:
        return True
    if n % 2 == 0:
        return False

    sqrt_n = int(math.floor(math.sqrt(n)))
    for i in range(3, sqrt_n + 1, 2):
        if n % i == 0:
            return False
    return True

def main():
    with concurrent.futures.ProcessPoolExecutor() as executor:
        for number, prime in zip(PRIMES, executor.map(is_prime, PRIMES)):
            print('%d is prime: %s' % (number, prime))

if __name__ == '__main__':
    main()

BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

In [102]:
from concurrent.futures import ThreadPoolExecutor, wait, as_completed
from time import sleep
from random import randint
 
def return_after_5_secs(num):
    sleep(randint(1, 5))
    return "Return of {}".format(num)
 
pool = ThreadPoolExecutor(5)
futures = []
for x in range(5):
    futures.append(pool.submit(return_after_5_secs, x))
 
#for x in as_completed(futures):
#    print(x.result())

print(wait(futures))

DoneAndNotDoneFutures(done={<Future at 0x2aa80e28848 state=finished returned str>, <Future at 0x2aa8154b648 state=finished returned str>, <Future at 0x2aa81563888 state=finished returned str>, <Future at 0x2aa81515348 state=finished returned str>, <Future at 0x2aa814c5188 state=finished returned str>}, not_done=set())

In [105]:
os.cpu_count()

8

In [107]:
import concurrent.futures
import urllib.request
 
URLS = ['http://www.foxnews.com/',
        'http://www.cnn.com/',
        'http://europe.wsj.com/',
        'http://www.bbc.co.uk/',
        'http://some-made-up-domain.com/']
 

def load_url(url, timeout):
    with urllib.request.urlopen(url, timeout=timeout) as conn:
        return conn.read()
 

with concurrent.futures.ProcessPoolExecutor(max_workers=5) as executor:
    
    future_to_url = {executor.submit(load_url, url, 60): url for url in URLS}
    print(future_to_url)
    for future in concurrent.futures.as_completed(future_to_url):
        url = future_to_url[future]
        try:
            data = future.result()
        except Exception as exc:
            print('%r generated an exception: %s' % (url, exc))
        else:
            print('%r page is %d bytes' % (url, len(data)))

{<Future at 0x2aa815b8448 state=running>: 'http://www.foxnews.com/', <Future at 0x2aa81513288 state=pending>: 'http://www.cnn.com/', <Future at 0x2aa815137c8 state=pending>: 'http://europe.wsj.com/', <Future at 0x2aa81513848 state=pending>: 'http://www.bbc.co.uk/', <Future at 0x2aa81513a08 state=pending>: 'http://some-made-up-domain.com/'}
'http://www.foxnews.com/' generated an exception: A process in the process pool was terminated abruptly while the future was running or pending.
'http://www.cnn.com/' generated an exception: A process in the process pool was terminated abruptly while the future was running or pending.
'http://europe.wsj.com/' generated an exception: A process in the process pool was terminated abruptly while the future was running or pending.
'http://www.bbc.co.uk/' generated an exception: A process in the process pool was terminated abruptly while the future was running or pending.
'http://some-made-up-domain.com/' generated an exception: A process in the process pool was terminated abruptly while the future was running or pending.

In [108]:
import concurrent.futures

nums = [1,2,3,4,5,6,7,8,9,10]

def f(x):
    return x * x
def main():
    # Make sure the map and function are working
    print([val for val in map(f, nums)])

    # Test to make sure concurrent map is working
    with concurrent.futures.ProcessPoolExecutor() as executor:
        print([val for val in executor.map(f, nums)])

if __name__ == '__main__':
    main()

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

In [109]:
!dir

 D 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 1018-302D

 D:\myProjects\pandas 디렉터리

2020-01-31  오전 06:26    <DIR>          .
2020-01-31  오전 06:26    <DIR>          ..
2020-01-22  오전 05:30    <DIR>          .ipynb_checkpoints
2020-01-03  오전 05:07    <DIR>          data
2020-01-03  오전 05:05         1,851,369 doit_pandas-master.zip
2020-01-03  오전 06:28             8,554 load_excel.xlsx
2020-01-03  오전 05:07    <DIR>          notebook
2020-01-03  오전 05:07    <DIR>          output
2018-09-04  오후 10:46               596 README.md
2020-01-31  오전 06:26            71,714 Untitled.ipynb
               4개 파일           1,932,233 바이트
               6개 디렉터리  605,221,691,392 바이트 남음

In [110]:
%pwd

'D:\\myProjects\\pandas'